artifacts_root: artifacts


data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/shivamsharma00/text_summarizer/raw/main/samsum.zip
  local_data_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion